### ISSUE TITLE
A List of Queries

### ISSUE THREAD

**Issue by jewells77** [VirtoCommerce/vc-theme-b2b-vue#495]
- In "content\pages\homepage.page" file Paths are not dynamic. It's hardcoded "/themes/assets/static/...". When we try to run Vue, this path won't work; the path should be "/assets/static/..." in vue.
- Do we use Nuxt? in package.json we couldn't find nuxt, but we could see it in "const { $graphqlClient } = useNuxtApp();"
- The language toggle is not working.
- The folder structures in the readme are not correct. Eg: currently in readme "core/api/graphql but the actual path is "xapi/graphql"

**Comment by artmakarov** [comment]
> The language toggle is not working.

@jewells77 Could you tell us more about that?
