### ISSUE TITLE
Unable to setup storefront with b2b-vue theme

### ISSUE THREAD

**Issue by shubhamdhanetia** [VirtoCommerce/vc-theme-b2b-vue#518]
Unable to see anything on Vue App : localhost:3000 or on storefront localhost:2082

1) Installed platform using vc-package file - modules_v3.json and running platform on http://localhost:5000/ with sample data.
2) Cloned storefront 6.15.0 
3) Cloned b2b-vue theme code. executed command yarn build
4) Created symbolic link from storefront to the theme code
![image](https://user-images.githubusercontent.com/71070755/232349834-0a9eb3cd-1d21-400c-9eb3-2a7cb6cd0953.png)
5) Running yarn dev command
![image](https://user-images.githubusercontent.com/71070755/232350305-037e783f-1495-4cce-8e90-1b9dc84dfc2d.png)
6) Can't see anything on storefront
![image](https://user-images.githubusercontent.com/71070755/232350342-514ec5b6-b0f8-4492-abca-9ebac09d5650.png)
7) Can't see anything on Vite App
![image](https://user-images.githubusercontent.com/71070755/232350387-f9080b3d-6412-4778-a101-9bcf72eeb8af.png)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8429 has been created

**Comment by asvishnyakov** [comment]
@shubhamdhanetia You need to run storefront with https on 2082 port or add `.env.local` file with actual https url to storefront in APP_BACKEND_URL variable.
