### ISSUE TITLE
Not working on port 3000

### ISSUE THREAD

**Issue by jewells77** [VirtoCommerce/vc-theme-b2b-vue#876]
We are trying to run vue code natively with "yarn dev", but it gives an error.

```pm [vite] http proxy error at /storefrontapi/theme/context:
Error: write EPROTO C85C0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
11:30:09 pm [vite] http proxy error at /xapi/graphql:
Error: write EPROTO C85C0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:355:

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)

[vue-tsc] Found 0 errors. Watching for file changes.
```

**Comment by asvishnyakov** [comment]
@jewells77 This is SSL/TLS (https) issue and probably not related to port at all. Do you use https for your `APP_BACKEND_URL` value? Is it trusted? (If it's self-signed certificate, such as used for ASP.NET Core local development, then you probably need to add it to trusted ceritifcates, for example by running `dotnet dev-certs https --trust`; you can check this by opening URL of your backend in browser)

**Comment by jewells77** [comment]
I have run the code with this option.
![image (2)](https://github.com/VirtoCommerce/vc-theme-b2b-vue/assets/79835068/c22edeba-a495-459a-90b7-e6e040167567)
and It ran in a different port, and I have changed that port in ".env" file in vue as well. It's working now.
