### ISSUE TITLE
Arabic language text alignment

### ISSUE THREAD

**Issue by jewells77** [VirtoCommerce/vc-theme-b2b-vue#877]
We have added the Arabic language content. It shows the text from left to right. We need Arabic from right to left. Do we have any configuration to have text start from right to left?

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8494 has been created

**Comment by NaMax66** [comment]
@jewells77 could you add a screenshot - where exactly do you want to display the content in Arabic and which shows the problem?
